// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFYx84TkM4LDRNO1EXiGHgylsgLmCWkaI',
    appId: '1:291922863219:web:5eeb7706d4524a7bdff606',
    messagingSenderId: '291922863219',
    projectId: 'vku-vietnamese-learning',
    authDomain: 'vku-vietnamese-learning.firebaseapp.com',
    storageBucket: 'vku-vietnamese-learning.firebasestorage.app',
    measurementId: 'G-7SJXLJY8NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDanXBW61wCUM973CKDMTAy52poB-R5Icc',
    appId: '1:291922863219:android:62fe401890c91080dff606',
    messagingSenderId: '291922863219',
    projectId: 'vku-vietnamese-learning',
    storageBucket: 'vku-vietnamese-learning.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYJYiD5yp5ioWL_aqohkIIXUNWQZ5ehuQ',
    appId: '1:291922863219:ios:810bfe36fdf99a3ddff606',
    messagingSenderId: '291922863219',
    projectId: 'vku-vietnamese-learning',
    storageBucket: 'vku-vietnamese-learning.firebasestorage.app',
    iosClientId: '291922863219-3rsk08eaohfgq1ibqfhnps16m07hqqru.apps.googleusercontent.com',
    iosBundleId: 'com.vku.duclab.vkuLearningApp',
  );
}
